influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistence
    # sudo mkdir -p /root/influxdb
    - /root/influxdb:/var/lib/influxdb
  restart:
    condition: unless-stopped 

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    # Data persistence
    - /root/grafana:/var/lib/grafana
  restart:
    condition: unless-stopped
