influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistence
    # sudo mkdir -p /root/influxdb
    - /root/influxdb:/var/lib/influxdb
  restart: unless-stopped 
  networks:
      influxdb_net:
          ipv4_address:172.28.1.1

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    # Data persistence
    # sudo mkdir -p /root/grafana; chown 472:472 /root/grafana/
    - /root/grafana:/var/lib/grafana
  restart: unless-stopped
  networks:
      grafana_net:
          ipv4_address:172.28.1.2
